all: compile

# Compiler
CC = gcc
# Source File
SRC = main.c
# Output File
OUT = main
# Compilation Flags
CFLAGS = -Wall -g

# Compiling
compile:
	$(CC) $(CFLAGS) $(SRC) -o $(OUT)

# Cleaning
clean:
	rm -f $(OUT)