# Makefiles are very useful for compiling and installing your source code

CFLAGS= -Wall -g
# CFLAGS are the extra arguments to be taken by the compiler while compiling the source 	
# -Wall tells the compiler to start debugging and display the error
# -g is for holding the error messages in the backtrace
clean:
	rm -f main
# rm is the UNIX command for removing files
# -f is the flag which means remove anything that exactly resemble main and force it
