# Optimize of debugging with -Og
# Enable debug symbols with in native format -g(#), # -> 1, 2(default), 3
# Enable debug symbols in format best for gdb with -ggdb
# Use Ctrl + X , a to enable GUI debugging

CFLAGS = -Wall -Wextra -Og -ggdb3

all: main